### ISSUE TITLE
Some information regarding pack and grafting

### ISSUE THREAD

**Issue by D4ndellion** [CuBeRJAN/nix-problems#1]
As far as my understanding goes, nixpkgs has supported something similar grafting for a while (11 years): https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/replace-dependency.nix but noone uses it, it's even mentioned in https://guix.gnu.org/blog/2016/timely-delivery-of-security-updates/ but there's afaik no recursive application of it

https://github.com/matthewbauer/nix-bundle was the goto equivalent for guix pack (and is 7 years old - pre guix pack) and the flake cli now has `nix bundle` built in (via https://github.com/NixOS/bundlers)

But you're completely right - guix does a lot of things better and has gotten a lot of benefit from learning from nixpkgs's mistakes

**Comment by lambdanil** [comment]
Hi,

thank you for the correction, I totally missed this - I'll update the article later.

**Comment by lambdanil** [comment]
Updated!
https://github.com/CuBeRJAN/nix-problems/commit/e72df51aadb797a9fd3b49c8be220b374fc94141
